/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import archivosObjetos.OperacionesTarjetaVisual;

/**
 *
 * @author Lab IV Incos La Paz
 */
public class MenuPrincipal extends javax.swing.JFrame {
    OperacionesTarjetaVisual obj;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        obj=new OperacionesTarjetaVisual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        registrarItm = new javax.swing.JMenuItem();
        mostrarItm = new javax.swing.JMenuItem();
        bloquearItm = new javax.swing.JMenuItem();
        desbloquearItm = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        depositoItm = new javax.swing.JMenuItem();
        retiroItm = new javax.swing.JMenuItem();
        saldoItm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Cliente");

        registrarItm.setText("Registrar Cliente");
        registrarItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarItmActionPerformed(evt);
            }
        });
        jMenu1.add(registrarItm);

        mostrarItm.setText("Mostrar clientes");
        jMenu1.add(mostrarItm);

        bloquearItm.setText("Bloquear Tarjeta");
        jMenu1.add(bloquearItm);

        desbloquearItm.setText("Desbloquear Tarjeta");
        jMenu1.add(desbloquearItm);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operaciones");

        depositoItm.setText("Deposito");
        jMenu2.add(depositoItm);

        retiroItm.setText("Retiro");
        jMenu2.add(retiroItm);

        saldoItm.setText("Saldo");
        jMenu2.add(saldoItm);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarItmActionPerformed
        // aperturando la venta de registro de cliente
        RegistrarCliente registrar=new RegistrarCliente();
        //pasando el objeto
        registrar.setOperaciones(obj);
        //el formulario adicionamos al escritorio
        escritorio.add(registrar);
        //visualizar
        registrar.show();
    }//GEN-LAST:event_registrarItmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bloquearItm;
    private javax.swing.JMenuItem depositoItm;
    private javax.swing.JMenuItem desbloquearItm;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mostrarItm;
    private javax.swing.JMenuItem registrarItm;
    private javax.swing.JMenuItem retiroItm;
    private javax.swing.JMenuItem saldoItm;
    // End of variables declaration//GEN-END:variables
}
